import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/sections/navigation/header";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Buying Buddy plugin v5.02 - DO NOT DEFER - Must load at the top */}
        <script src="https://www.mbb2.com/version3/css/theme/acid/ghEb9eob" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              var MBB = {seo : "false",data:{ acid : "ghEb9eob" } };
              function mbbMapLoaded(){ MBB.googleMaps = true; };
            `,
          }}
        />
        {/* NOTE: Add your Google Maps API Key in the src below */}
        <script src="https://maps.googleapis.com/maps/api/js?callback=mbbMapLoaded&libraries=places" />
        <script src="https://d2w6u17ngtanmy.cloudfront.net/scripts/my-buying-buddy.5.0.js.gz" />
        {/* End Buying Buddy Plugin */}
      </head>
      <body
        className={`${outfit.variable} antialiased font-sans`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
